# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://avikumarraj.github.io
baseurl:          /

author:
  name:           'Avi'
  url:            https://x.com/avikumarraj

paginate:         5
paginate_path:    "/blog/page:num/"


# Custom vars
version:          

github: https://github.com/avikumarraj/avikumarraj.github.io

sidebar_blog_link:  '/blog'

